FROM postgres:15-alpine

# Variáveis de ambiente padrão
ENV POSTGRES_DB=ticketwallet
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres

EXPOSE 5432

# O script init-db.sh será executado automaticamente pelo postgres:15-alpine
# quando o banco for inicializado pela primeira vez

